### ISSUE TITLE
Phaser Webcam in bower!

### ISSUE THREAD

**Issue by jdnichollsc** [jotson/phaser-webcam#1]
Hi man,

Can you upload this useful library to bower?

Thanks in advance, Nicholls

**Comment by jotson** [comment]
It's not a library. But you're welcome to fork it.

**Comment by jdnichollsc** [comment]
Ohh sorry,

Who is the creator of this plugin? Phaser team?

Regards

**Comment by jotson** [comment]
My version is adapted from the example on the Phaser website. http://phaser.io/examples/v2/misc/webcam
